services:
  - type: web
    name: book-ur-seat
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn book_ur_seat.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DJANGO_SETTINGS_MODULE
        value: book_ur_seat.settings
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://book_ur_seat_user:mBxarEuxixaX1snmGqiLnKZp5eyhtE0H@dpg-d2f20rk9c44c739i9oe0-a.oregon-postgres.render.com/book_ur_seat"