# Generated by Django 5.2.6 on 2025-09-20 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_eventcategory_liveevent_eventbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Event Seat Categories',
            },
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='num_tickets',
        ),
        migrations.CreateModel(
            name='EventSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=1)),
                ('number', models.PositiveIntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.liveevent')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.eventseatcategory')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('event', 'row', 'number')},
            },
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='movies.eventseat'),
        ),
    ]
